#!/usr/bin/env node
/**
 * Sync dev-standards/permissions/manifest.json → multi-agent permission configs.
 *
 * Usage:
 *   node scripts/permissions-sync.mjs [--dry-run] [--user] [--project PATH] [--overlay NAME]
 *
 * Default: --dry-run only (prints paths). Use --user to apply to home directory configs.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const MANIFEST_PATH = join(ROOT, 'permissions/manifest.json');
const OVERLAYS_DIR = join(ROOT, 'permissions/overlays');
const GENERATED_DIR = join(ROOT, 'permissions/generated');

const args = process.argv.slice(2);
const dryRun = !args.includes('--user') && !args.includes('--project');
const applyUser = args.includes('--user');
const projectIdx = args.indexOf('--project');
const projectPath = projectIdx >= 0 ? resolve(args[projectIdx + 1] || '') : null;
const overlayIdx = args.indexOf('--overlay');
const overlayName = overlayIdx >= 0 ? args[overlayIdx + 1] : null;

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function writeMaybe(path, content, label) {
  if (dryRun && !applyUser && !projectPath) {
    console.log(`[dry-run] would write ${label}: ${path}`);
    return;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
  console.log(`→ wrote ${label}: ${path}`);
}

function mergeRules(manifest, overlay) {
  const rules = [...manifest.rules];
  if (overlay?.rules) {
    const byId = new Map(rules.map((r) => [r.id, r]));
    for (const r of overlay.rules) {
      byId.set(r.id, r);
    }
    return [...byId.values()];
  }
  return rules;
}

function mergeAutoRun(manifest, overlay) {
  const base = manifest.autoRun || {};
  const extra = overlay?.autoRun || {};
  return {
    allow_instructions: [...(base.allow_instructions || []), ...(extra.allow_instructions || [])],
    block_instructions: [...(base.block_instructions || []), ...(extra.block_instructions || [])],
  };
}

function activeRules(rules) {
  return rules.filter((r) => r.status === 'active');
}

function patternsForTier(rules, tier) {
  const out = [];
  for (const r of activeRules(rules)) {
    if (r.tier === tier) {
      out.push(...r.patterns);
    }
  }
  return [...new Set(out)];
}

function toClaudeBash(pattern) {
  const trimmed = pattern.trim();
  if (trimmed.endsWith('*')) return `Bash(${trimmed})`;
  return `Bash(${trimmed}*)`;
}

function toClaudeDeny(pattern) {
  const trimmed = pattern.trim();
  if (trimmed.endsWith('*')) return `Bash(${trimmed})`;
  return `Bash(${trimmed} *)`;
}

function toOpencodeKey(pattern) {
  const trimmed = pattern.trim();
  if (trimmed.includes('*')) return trimmed;
  return `${trimmed}*`;
}

function toCodexPattern(pattern) {
  return pattern.trim().split(/\s+/).filter(Boolean);
}

function buildCursorPermissions(checkPatterns, autoRun) {
  return {
    terminalAllowlist: checkPatterns,
    autoRun,
  };
}

function buildClaudePermissions(checkPatterns, denyPatterns) {
  const allow = [
    'Read',
    'Grep',
    'Glob',
    ...checkPatterns.map(toClaudeBash),
  ];
  const deny = denyPatterns.map(toClaudeDeny);
  return { allow, deny };
}

function buildOpencodePermissions(checkPatterns, denyPatterns) {
  const bash = { '*': 'ask' };
  for (const p of checkPatterns) {
    bash[toOpencodeKey(p)] = 'allow';
  }
  for (const p of denyPatterns) {
    bash[toOpencodeKey(p)] = 'deny';
  }
  return { bash };
}

function buildCodexRules(checkPatterns, denyPatterns) {
  const lines = [
    '# Generated by dev-standards permissions-sync — do not edit by hand',
    '# Source: permissions/manifest.json',
    '',
  ];
  for (const p of checkPatterns) {
    const pat = toCodexPattern(p);
    const patStr = JSON.stringify(pat).replace(/"/g, '"');
    lines.push(
      `prefix_rule(pattern = ${JSON.stringify(pat)}, decision = "allow", justification = "dev-standards check tier")`,
      '',
    );
  }
  for (const p of denyPatterns) {
    const pat = toCodexPattern(p);
    lines.push(
      `prefix_rule(pattern = ${JSON.stringify(pat)}, decision = "forbidden", justification = "dev-standards deny tier")`,
      '',
    );
  }
  return lines.join('\n');
}

function buildAntigravityToml(checkPatterns) {
  const lines = [
    '# Generated by dev-standards permissions-sync',
    '# Place under ~/.gemini/policies/ (Antigravity)',
    '',
  ];
  let priority = 100;
  for (const p of checkPatterns) {
    lines.push('[[rule]]');
    lines.push('toolName = "run_shell_command"');
    lines.push(`commandPrefix = "${p.replace(/"/g, '\\"')}"`);
    lines.push('decision = "allow"');
    lines.push(`priority = ${priority}`);
    lines.push('');
    priority += 1;
  }
  return lines.join('\n');
}

function mergeJsonFile(path, mergeFn) {
  const existing = existsSync(path) ? readJson(path) : {};
  const merged = mergeFn(existing);
  return JSON.stringify(merged, null, 2) + '\n';
}

function applyUserConfigs(checkPatterns, denyPatterns, autoRun) {
  const home = process.env.HOME || process.env.USERPROFILE || '';
  if (!home) {
    console.error('error: HOME not set');
    process.exit(1);
  }

  const cursorPath = join(home, '.cursor/permissions.json');
  const cursorBody = buildCursorPermissions(checkPatterns, autoRun);
  writeMaybe(cursorPath, JSON.stringify(cursorBody, null, 2) + '\n', 'Cursor permissions.json');

  const claudePath = join(home, '.claude/settings.json');
  const claudePerms = buildClaudePermissions(checkPatterns, denyPatterns);
  const claudeContent = mergeJsonFile(claudePath, (existing) => ({
    ...existing,
    permissions: {
      ...(existing.permissions || {}),
      allow: [...new Set([...(existing.permissions?.allow || []), ...claudePerms.allow])],
      deny: [...new Set([...(existing.permissions?.deny || []), ...claudePerms.deny])],
    },
  }));
  writeMaybe(claudePath, claudeContent, 'Claude Code settings.json');

  const codexDir = join(home, '.codex/rules');
  const codexPath = join(codexDir, 'dev-standards.rules');
  writeMaybe(codexPath, buildCodexRules(checkPatterns, denyPatterns), 'Codex dev-standards.rules');

  const opencodePath = join(home, '.config/opencode/opencode.json');
  const opencodePerm = buildOpencodePermissions(checkPatterns, denyPatterns);
  const opencodeContent = mergeJsonFile(opencodePath, (existing) => ({
    ...existing,
    $schema: existing.$schema || 'https://opencode.ai/config.json',
    permission: {
      ...(existing.permission || {}),
      bash: {
        ...(existing.permission?.bash || {}),
        ...opencodePerm.bash,
      },
    },
  }));
  writeMaybe(opencodePath, opencodeContent, 'OpenCode opencode.json');

  const geminiDir = join(home, '.gemini/policies');
  const antigravityPath = join(geminiDir, 'dev-standards-check.toml');
  writeMaybe(antigravityPath, buildAntigravityToml(checkPatterns), 'Antigravity policies TOML');
}

function applyProjectConfigs(projectRoot, checkPatterns, denyPatterns, autoRun) {
  const cursorPath = join(projectRoot, '.cursor/permissions.json');
  const cursorBody = buildCursorPermissions(checkPatterns, autoRun);
  writeMaybe(cursorPath, JSON.stringify(cursorBody, null, 2) + '\n', 'project Cursor permissions.json');

  const codexDir = join(projectRoot, '.codex/rules');
  const codexPath = join(codexDir, 'dev-standards.rules');
  writeMaybe(codexPath, buildCodexRules(checkPatterns, denyPatterns), 'project Codex rules');
}

function main() {
  const manifest = readJson(MANIFEST_PATH);
  let overlay = null;

  if (overlayName) {
    const overlayPath = join(OVERLAYS_DIR, `${overlayName}.json`);
    if (!existsSync(overlayPath)) {
      console.error(`error: overlay not found: ${overlayPath}`);
      process.exit(1);
    }
    overlay = readJson(overlayPath);
  } else if (projectPath) {
    const basename = projectPath.split('/').pop();
    const overlayPath = join(OVERLAYS_DIR, `${basename}.json`);
    if (existsSync(overlayPath)) {
      overlay = readJson(overlayPath);
      console.log(`→ loaded overlay: ${overlayPath}`);
    }
  }

  const rules = mergeRules(manifest, overlay);
  const autoRun = mergeAutoRun(manifest, overlay);
  const checkPatterns = patternsForTier(rules, 'check');
  const denyPatterns = patternsForTier(rules, 'deny');

  mkdirSync(GENERATED_DIR, { recursive: true });
  writeFileSync(
    join(GENERATED_DIR, 'cursor-permissions.json'),
    JSON.stringify(buildCursorPermissions(checkPatterns, autoRun), null, 2) + '\n',
  );
  writeFileSync(
    join(GENERATED_DIR, 'claude-permissions.json'),
    JSON.stringify(buildClaudePermissions(checkPatterns, denyPatterns), null, 2) + '\n',
  );
  writeFileSync(join(GENERATED_DIR, 'codex-dev-standards.rules'), buildCodexRules(checkPatterns, denyPatterns));
  writeFileSync(
    join(GENERATED_DIR, 'opencode-permission.json'),
    JSON.stringify(buildOpencodePermissions(checkPatterns, denyPatterns), null, 2) + '\n',
  );
  writeFileSync(join(GENERATED_DIR, 'antigravity-check.toml'), buildAntigravityToml(checkPatterns));
  console.log(`→ preview: ${GENERATED_DIR}/`);

  if (applyUser) {
    applyUserConfigs(checkPatterns, denyPatterns, autoRun);
  }

  if (projectPath) {
    applyProjectConfigs(projectPath, checkPatterns, denyPatterns, autoRun);
  }

  if (dryRun && !applyUser && !projectPath) {
    console.log('\nPass --user to apply globally, or --project PATH for repo overlay.');
  }

  const deprecated = rules.filter((r) => r.status === 'deprecated');
  if (deprecated.length) {
    console.log(`\n⚠️  ${deprecated.length} deprecated rule(s) still in manifest (not deployed):`);
    for (const r of deprecated) {
      console.log(`   - ${r.id}`);
    }
  }
}

main();
